# Generated by Django 5.1 on 2024-08-22 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='content',
            name='servings',
        ),
        migrations.CreateModel(
            name='NutritionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.IntegerField()),
                ('calories', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_info', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'NutritionalInfo',
                'verbose_name_plural': 'NutritionalInfos',
            },
        ),
    ]
