# Generated by Django 5.1 on 2024-08-22 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_content_calories_remove_content_servings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='content',
            name='cuisine',
        ),
        migrations.AddField(
            model_name='recipe',
            name='courses',
            field=models.ManyToManyField(related_name='recipes', to='recipes.course'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.cuisine'),
            preserve_default=False,
        ),
    ]
