# Generated by Django 5.1 on 2024-08-23 17:13

import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Maximum file size allowed is 2Mb', null=True, upload_to='category_images/', validators=[recipes.models.validate_image]),
        ),
    ]
