# Generated by Django 5.1 on 2024-08-19 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_cuisine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cook_time', models.CharField(max_length=50)),
                ('prep_time', models.CharField(max_length=50)),
                ('total_time', models.CharField(max_length=50)),
                ('servings', models.IntegerField()),
                ('calories', models.DecimalField(decimal_places=2, max_digits=10)),
                ('courses', models.ManyToManyField(related_name='recipes', to='recipes.course')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.cuisine')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
            },
        ),
    ]
