# Generated by Django 5.1 on 2024-08-21 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cook_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='content',
            name='prep_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='content',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
