# Generated by Django 5.1 on 2024-08-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_content_cook_time_alter_content_prep_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cook_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='prep_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='total_time',
            field=models.DurationField(),
        ),
    ]
